# Mehr Heap für den Gradle-Daemon ? behebt den OutOfMemoryError
org.gradle.jvmargs=-Xmx2560m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8

# Separater, kleinerer Heap für den Kotlin-Compile-Daemon
kotlin.daemon.jvmargs=-Xmx1536m

org.gradle.parallel=true
org.gradle.caching=true

# Pflicht, da das Projekt AndroidX-Bibliotheken verwendet
android.useAndroidX=true
android.nonTransitiveRClass=true